### ISSUE TITLE
Missing 1 required positional argument for tsfresh features

### ISSUE THREAD

**Issue by MislavSag** [hendersontrent/theft#154]
When I try to calculate tsfresh features I get an error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: extract_relevant_features() missing 1 required positional argument: 'y' 
```
Can you check one more time your code for tsfresh is working?

**Comment by lfaucheux** [comment]
There is no need to reproduce anything actually. Having a look at [`tsfel_calculator.py`](https://github.com/hendersontrent/theft/blob/main/inst/python/tsfresh_calculator.py) is enough. At [line 17](https://github.com/hendersontrent/theft/blob/main/inst/python/tsfresh_calculator.py#L17) it reads 

```
# [...]    
    # [...]
    if cleanup == "Yes":
        extracted_features = extract_relevant_features(timeseries, column_id = column_id, column_sort = column_sort)
    # [...]
```

But it turns out that [`extract_relevant_features`](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.convenience.html#module-tsfresh.convenience.relevant_extraction), mobilized as soon as [`tsfresh_cleanup=TRUE`](https://rdrr.io/cran/theft/man/calculate_features.html) takes another (positional) argument, i.e. a *target vector* named `y`, which very likely echoes `group_var`. Hence the error highlighted by @MislavSag. As a result, it follows that the above code should rather look like

```
# [...]    
    # [...]
    if cleanup == "Yes":
        extracted_features = extract_relevant_features(timeseries, classes, column_id = column_id, column_sort = column_sort)
    # [...]                                                        ^^^^^^^
```
Don't you think so ?

**Comment by hendersontrent** [comment]
Hi @lfaucheux and @MislavSag thank you for this. I believe I have fixed the error (and many other things) in the most recent version (v0.4.2.1) that is now available on `main` on GitHub. I am yet to submit it to CRAN. Note that there are many breaking changes in this version, but I believe they are for the better, so please check out the vignette and docs!
